### ISSUE TITLE
unable to configure "agent_host": parameter using environment variable 

### ISSUE THREAD

**Issue by siqusoft** [DataDog/dd-opentracing-cpp#144]
i was using the dd agent in kubernetes enviroment where host name is dynamic and currently unable to configure the tracer. can these settings be populated as envinroment variables as well?

**Comment by cgilmour** [comment]
Hi @siqusoft, yes it can. The `DD_AGENT_HOST` environment variable can be set using the downward API.

```yaml
- name: DD_AGENT_HOST
  valueFrom:
    fieldRef:
      fieldPath: status.hostIP
```
