### ISSUE TITLE
Duplicate Tracer Request Headers

### ISSUE THREAD

**Issue by iAnomaly** [DataDog/dd-opentracing-cpp#272]
Hi, we are using the `dd-opentracing-cpp` component of the `nginx-opentracing` module in the NGINX Ingress Controller and are seeing duplicate trace related headers being added to all requests from NGINX to upstreams. An example upstream is concatenating the duplicate headers with comma delimiter such that:
```
x-b3-traceid: 2de81f1d098a4b58
...
x-b3-traceid: 2de81f1d098a4b58
```
becomes
```
x-b3-traceid: 2de81f1d098a4b58, 2de81f1d098a4b58
```

This is breaking the [Zipkin header specification](https://github.com/openzipkin/b3-propagation#traceid) for upstreams who follow [RFC spec on duplicate headers](https://httpwg.org/specs/rfc7230.html#field.order).  Namely:

> A sender MUST NOT generate multiple header fields with the same field name in a message unless either the entire field value for that header field is defined as a comma-separated list [i.e., #(values)] or the header field is a well-known exception (as noted below).
> 
> A recipient MAY combine multiple header fields with the same field name into one "field-name: field-value" pair, without changing the semantics of the message, by appending each subsequent field value to the combined field value in order, separated by a comma. The order in which header fields with the same field name are received is therefore significant to the interpretation of the combined field value; a proxy MUST NOT change the order of these field values when forwarding a message.

#### Example headers from a request originating from NGINX:
```
Headers
x-b3-traceid
2de81f1d098a4b58
x-b3-traceid
2de81f1d098a4b58
x-b3-spanid
c8c4154bc0e63e54
x-b3-sampled
1
x-b3-sampled
1
x-datadog-tags
_dd.p.dm=-3
x-datadog-tags
_dd.p.dm=-3
host
<REDACTED>
x-request-id
a4b9ed78e82199dff1a5143a8d9caa4f
x-real-ip
10.1.101.199
x-forwarded-for
24.74.105.136, 10.1.101.199
x-forwarded-host
<REDACTED>
x-forwarded-port
443
x-forwarded-proto
https
x-forwarded-scheme
https
x-scheme
https
x-original-forwarded-for
24.74.105.136
x-amzn-trace-id
Root=1-64ef7cce-7d84acea11b17b88641f8b3f
accept
application/json, text/plain, */*
x-device-id
<REDACTED>
x-device-version
1.3
x-device-platform
www
x-client-timezone
America/New_York
x-session-token
<REDACTED>
x-www-req-from
/_next/static/chunks/pages/polls/success.js
user-agent
axios/0.26.1
x-datadog-trace-id
3516517757488871833
x-datadog-parent-id
2844984760881017417
x-datadog-sampling-priority
1
traceparent
00-000000000000000030cd2e44e57a3999-277b6a910fb67249-01
tracestate
dd=t.dm:-1;s:1
```

#### Versions:
* ingress-nginx controller: 1.81
* ingress-nginx: Helm Chart: 4.7.1
* dd-opentracing-cpp: 1.3.7

#### Configuration (Helm Chart values):
```yaml
...
          config:
            compute-full-forwarded-for: true
            datadog-collector-host: $DD_AGENT_HOST
            enable-opentracing: true
            http-snippet: |
              proxy_cache_path /tmp/nginx-cache-web-www levels=1:2 keys_zone=web-www:10m max_size=1g inactive=8h use_temp_path=off;
            keep-alive-requests: "4294967295" # uint32 # https://github.com/nginx/nginx/blob/release-1.21.6/src/http/ngx_http_core_module.c#L1342
            location-snippet: |
              opentracing_operation_name   "$request_method $uri";
              opentracing_tag              "resource.name" "$uri";
              opentracing_propagate_context;
            main-snippet: |
              env DD_AGENT_HOST;
              env DD_ENV;
              env DD_SERVICE;
              env DD_VERSION;
              env DD_PROPAGATION_STYLE_INJECT;
              env DD_PROPAGATION_STYLE_EXTRACT;
              env DD_TRACE_SAMPLE_RATE;
            max-worker-open-files: 261888 # 1048576 - 1024 / 4 # process user's file descriptor limit [ulimit -n] - 1024 / resource.limits.cpu
            proxy-body-size: 100m
            proxy-headers-hash-bucket-size: 128
            proxy-headers-hash-max-size: 1024
            proxy-real-ip-cidr: 10.0.0.0/8
            use-forwarded-headers: true
            use-proxy-protocol: true
          extraArgs:
            post-shutdown-grace-period: 0 # https://github.com/kubernetes/ingress-nginx/blob/controller-v1.8.0/pkg/util/process/sigterm.go#L45
            shutdown-grace-period: 240 # https://github.com/kubernetes/ingress-nginx/blob/controller-v1.8.0/internal/ingress/controller/nginx.go#L378
          extraEnvs:
          - name: DD_ENV
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['tags.datadoghq.com/env']
          - name: DD_SERVICE
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['tags.datadoghq.com/service']
          - name: DD_VERSION
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['tags.datadoghq.com/version']
          - name: DD_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: DD_ENTITY_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.uid
          - name: DD_PROPAGATION_STYLE_EXTRACT
            value: B3
          - name: DD_PROPAGATION_STYLE_INJECT
            value: B3
          - name: DD_TRACE_SAMPLE_RATE
            value: "1"
          labels:
            tags.datadoghq.com/env: {{ requiredEnv "ENV" }}
            tags.datadoghq.com/service: ingress-nginx
            tags.datadoghq.com/version: {{ $version | quote }}
```
